# Generated by Django 2.0 on 2017-12-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(null=True)),
                ('heart_rate', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('sync_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(null=True)),
                ('activity', models.CharField(max_length=32, null=True)),
                ('intensity', models.FloatField(null=True)),
                ('start_timestamp', models.DateTimeField(null=True)),
                ('stop_timestamp', models.DateTimeField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('sync_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestingHeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(null=True)),
                ('rest_heart_rate', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('sync_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepCalories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(null=True)),
                ('start_timestamp', models.DateTimeField(null=True)),
                ('stop_timestamp', models.DateTimeField(null=True)),
                ('step', models.IntegerField(null=True)),
                ('total_calories', models.IntegerField(null=True)),
                ('sync_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(null=True)),
                ('stress', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('sync_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
