# Generated by Django 2.0 on 2017-12-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartrate',
            name='status',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
